In [3]:
import keras
print(keras.__version__)

2.10.0


In [ ]:
from keras import layers
inputs = layers.Input(shape=(1,))
layer1 = layers.Dense(512, activation="relu")(inputs)
outputs = layers.Dense(3, activation="linear")(layer1)
nn_model = keras.Model(inputs=inputs, outputs=outputs)
nn_model.summary()

In [ ]:
output = nn_model(0.5) #throws erros

In [ ]:
input = keras.backend.constant([[0.5]])
output = nn_model(input)
print(output)

In [ ]:
import numpy as np
inputs = np.arange(0, 1.1, 0.1)
input = keras.backend.constant([[0.5]])
input2 = keras.backend.constant([inputs])
output = nn_model(input)
print(input)
print(input2)
print(output)
print(inputs)

In [ ]:
import gym
e = gym.make('MountainCarContinuous-v0')
e.reset()
e.render()

In [ ]:
import gym
e = gym.make('MountainCarContinuous-v0')
s1 = e.reset()
print(s1)

In [ ]:
e.action_space.sample()

In [ ]:
from keras import layers
inputs = layers.Input(shape=(2, ))
layer1 = layers.Dense(512, activation="relu")(inputs)
outputs = layers.Dense(1, activation="linear")(layer1)
nn_model = keras.Model(inputs=inputs, outputs=outputs)
s = e.reset()
input = keras.backend.constant([s])
a = nn_model(input)
s,r,d,i = e.step(a)
print(s)

In [ ]:
# Control the agent with the network
from keras import layers
inputs = layers.Input(shape=(2, ))
layer1 = layers.Dense(512, activation="relu")(inputs)
outputs = layers.Dense(1, activation="linear")(layer1)
nn_model = keras.Model(inputs=inputs, outputs=outputs)
for item in range(10):
    s = e.reset()
    input = keras.backend.constant([s])
    a = nn_model(input)
    s,r,d,i = e.step(a)
    e.render()

In [ ]:
s = e.reset()
input = keras.backend.constant([s]) # s is an array
a = nn_model(input)
s,r,d,i = e.step(a)
print(s)

In [1]:
# Breakwall enviroment again
import keras
import gym
# We get a discrete (4) action space
env_name = "gym_gs:BreakwallNoFrameskip-v1"
e = gym.make(env_name)
s = e.reset()
print(e.action_space)

pygame 2.1.2 (SDL 2.0.18, Python 3.10.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
Discrete(4)


In [2]:
for i in range(4):
    print(e.action_space.sample())
    print("Observation/ state shape:", s.shape)

2
Observation/ state shape: (600, 780, 3)
0
Observation/ state shape: (600, 780, 3)
3
Observation/ state shape: (600, 780, 3)
0
Observation/ state shape: (600, 780, 3)


In [3]:
# We'll update the imput layer
from keras import layers
inputs = layers.Input(shape=(600,780,3,))
layer1 = layers.Flatten()(inputs) # We flatten the the 3D input layer
layer2 = layers.Dense(512, activation="relu")(layer1)
outputs = layers.Dense(4, activation="linear")(layer2)
nn_model = keras.Model(inputs=inputs, outputs=outputs)
state = e.reset()
state_tensor = keras.backend.constant(state)
state_tensor = keras.backend.expand_dims(state_tensor, 0)
action_values = nn_model(state_tensor)
print(action_values)

tf.Tensor([[0. 0. 0. 0.]], shape=(1, 4), dtype=float32)


In [ ]:
action = keras.backend.argmax(action_values[0]).numpy()
action = tf.argmax(action_probs[0]).numpy() # if renamed
print(keras.backend.argmax([0.1,0.5,0.01,0.2]).numpy())

In [4]:
state = e.reset()
state,r,d,i = e.step(1)
for i in range(10):
    state_tensor = keras.backend.constant(state)
    state_tensor = keras.backend.expand_dims(state_tensor, 0)
    action_values = nn_model(state_tensor)
    action = keras.backend.argmax(action_values[0]).numpy()
    print(action_values, action)
    state,r,d,i = e.step(1)
    e.render()

tf.Tensor([[-135.33052    -34.96535     -2.6175923  104.20433  ]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-133.47585    -40.308247    -9.9967165  100.298096 ]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-133.52586   -34.83712    -9.089392  106.48525 ]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-142.65623   -37.653713  -12.290092  100.456726]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-139.46967   -29.941523  -15.024807  102.14433 ]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-137.86325   -28.1824    -18.672073  102.72069 ]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-134.41286   -29.641228  -12.233908  105.396324]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-139.85345    -27.45109    -11.1273575   93.42384  ]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-134.20053   -29.01193   -11.014997   94.585106]], shape=(1, 4), dtype=float32) 3
tf.Tensor([[-136.16206   -31.467659   -6.581274   96.69547 ]], shape=(1, 4), dtype=float32) 3
